### ISSUE TITLE
pip install -r requirements.txt [Errors]

### ISSUE THREAD

**Issue by BenjaminHCCarr** [OpenHumans/genevieve#6]
Two errors/additions in the README.md

psycopg2==2.6.1 require PostgreSQL: the package requires "pg_config" in $PATH, which requires PostgreSQL be installed, normal on a dev box, but I had been using MariaDB so had to do a parrallel install.

Need to require Python2.7:
wsgiref is only available for python2.7, does not install with any version of python3 [3 or 3.5].

**Comment by madprime** [comment]
Hey, this is very cool that you tried this out! I'm looking at dusting this off.

FWIW, this code evolved and is currently set up to only receive VCF files via retrieval as an Open Humans project. Other stuff became specific to Open Humans features (e.g. accounts).

The README hasn't been updated to reflect this. Sorry. (There was so little interest, I wasn't bothering to update it.) This web app is now not very reusable, but it could be forked and modified to accept an uploaded file, not rely on Open Humans for accounts, etc.

My hope has been to set this up as an active project on Open Humans, so anyone with genetic data in Open Humans can generate a report. But the board had legal concerns and I haven't had an opportunity to follow up and resolve them.

**Comment by madprime** [comment]
Okay, I decided to make this all Python 3. It seems to be working with that now, including on Heroku. I haven't tested with Python 2.

README is also updated now to explain the limited reusability...
